function Run_Selected_Functions1()

%make_cortical_uv_binary_Unloaded();

BoneStats_Script_Cortical_Unloaded();

%Test Run #1 (Samples R55, R66, R69)
%{

spec_name =

55

Processing R55 ROI1 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0110 ... 
Processing UV image 0120 ... 
Processing UV image 0130 ... 
Processing UV image 0140 ... 
Processing UV image 0150 ... 
Processing UV image 0160 ... 
Processing UV image 0170 ... 
Processing UV image 0180 ... 
Processing UV image 0190 ... 
Processing UV image 0200 ... 
Processing UV image 0210 ... 
Processing UV image 0220 ... 
Processing UV image 0230 ... 
Processing UV image 0240 ... 
Processing UV image 0250 ... 
Processing UV image 0260 ... 
Processing UV image 0270 ... 
Processing UV image 0280 ... 
Processing UV image 0290 ... 
Processing UV image 0300 ... 
Processing UV image 0310 ... 
Processing UV image 0320 ... 
Processing UV image 0330 ... 
Processing UV image 0340 ... 
Processing UV image 0350 ... 
Processing UV image 0360 ... 
Saving specimen R55 ROI1 in matlab form ...
Warning: Variable 'surface_masks' cannot be saved to a MAT-file whose version is older than 7.3.
To save this variable, use the -v7.3 switch.
Skipping... 
> In Make_MillData_Highres_Cortical at 259
  In make_cortical_uv_binary_Unloaded at 29
  In Run_Selected_Functions1 at 5
Elapsed time is 5339.958612 seconds.
Processing R55 ROI2 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0480 ... 
Processing UV image 0490 ... 
Processing UV image 0500 ... 
Processing UV image 0510 ... 
Processing UV image 0520 ... 
Processing UV image 0530 ... 
Processing UV image 0540 ... 
Processing UV image 0550 ... 
Processing UV image 0560 ... 
Processing UV image 0570 ... 
Processing UV image 0580 ... 
Processing UV image 0590 ... 
Processing UV image 0600 ... 
Processing UV image 0610 ... 
Processing UV image 0620 ... 
Processing UV image 0630 ... 
Processing UV image 0640 ... 
Processing UV image 0650 ... 
Processing UV image 0660 ... 
Processing UV image 0670 ... 
Processing UV image 0680 ... 
Processing UV image 0690 ... 
Processing UV image 0700 ... 
Processing UV image 0710 ... 
Processing UV image 0720 ... 
Processing UV image 0730 ... 
Saving specimen R55 ROI2 in matlab form ...
Warning: Variable 'surface_masks' cannot be saved to a MAT-file whose version is older than 7.3.
To save this variable, use the -v7.3 switch.
Skipping... 
> In Make_MillData_Highres_Cortical at 259
  In make_cortical_uv_binary_Unloaded at 29
  In Run_Selected_Functions1 at 5
Elapsed time is 5112.802322 seconds.
Processing R55 ROI3 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0370 ... 
Processing UV image 0380 ... 
Processing UV image 0390 ... 
Processing UV image 0400 ... 
Processing UV image 0410 ... 
Processing UV image 0420 ... 
Processing UV image 0430 ... 
Processing UV image 0440 ... 
Processing UV image 0450 ... 
Processing UV image 0460 ... 
Processing UV image 0470 ... 
Saving specimen R55 ROI3 in matlab form ...
Warning: Variable 'surface_masks' cannot be saved to a MAT-file whose version is older than 7.3.
To save this variable, use the -v7.3 switch.
Skipping... 
> In Make_MillData_Highres_Cortical at 259
  In make_cortical_uv_binary_Unloaded at 29
  In Run_Selected_Functions1 at 5
Elapsed time is 1226.850567 seconds.

spec_name =

66

Processing R66 ROI1 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0200 ... 
Processing UV image 0210 ... 
Processing UV image 0220 ... 
Processing UV image 0230 ... 
Processing UV image 0240 ... 
Processing UV image 0250 ... 
Processing UV image 0260 ... 
Processing UV image 0270 ... 
Processing UV image 0280 ... 
Processing UV image 0290 ... 
Processing UV image 0300 ... 
Processing UV image 0310 ... 
Processing UV image 0320 ... 
Processing UV image 0330 ... 
Processing UV image 0340 ... 
Processing UV image 0350 ... 
Processing UV image 0360 ... 
Processing UV image 0370 ... 
Processing UV image 0380 ... 
Processing UV image 0390 ... 
Processing UV image 0400 ... 
Processing UV image 0410 ... 
Processing UV image 0420 ... 
Processing UV image 0430 ... 
Processing UV image 0440 ... 
Processing UV image 0450 ... 
Saving specimen R66 ROI1 in matlab form ...
Warning: Variable 'surface_masks' cannot be saved to a MAT-file whose version is older than 7.3.
To save this variable, use the -v7.3 switch.
Skipping... 
> In Make_MillData_Highres_Cortical at 259
  In make_cortical_uv_binary_Unloaded at 29
  In Run_Selected_Functions1 at 5
Elapsed time is 3436.521144 seconds.
Processing R66 ROI2 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0710 ... 
Processing UV image 0720 ... 
Processing UV image 0730 ... 
Processing UV image 0740 ... 
Processing UV image 0750 ... 
Processing UV image 0760 ... 
Processing UV image 0770 ... 
Processing UV image 0780 ... 
Processing UV image 0790 ... 
Processing UV image 0800 ... 
Processing UV image 0810 ... 
Processing UV image 0820 ... 
Processing UV image 0830 ... 
Processing UV image 0840 ... 
Processing UV image 0850 ... 
Processing UV image 0860 ... 
Processing UV image 0870 ... 
Processing UV image 0880 ... 
Processing UV image 0890 ... 
Processing UV image 0900 ... 
Processing UV image 0910 ... 
Processing UV image 0920 ... 
Processing UV image 0930 ... 
Processing UV image 0940 ... 
Processing UV image 0950 ... 
Processing UV image 0960 ... 
Saving specimen R66 ROI2 in matlab form ...
Warning: Variable 'surface_masks' cannot be saved to a MAT-file whose version is older than 7.3.
To save this variable, use the -v7.3 switch.
Skipping... 
> In Make_MillData_Highres_Cortical at 259
  In make_cortical_uv_binary_Unloaded at 29
  In Run_Selected_Functions1 at 5
Elapsed time is 3383.007164 seconds.
Processing R66 ROI3 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0460 ... 
Processing UV image 0470 ... 
Processing UV image 0480 ... 
Processing UV image 0490 ... 
Processing UV image 0500 ... 
Processing UV image 0510 ... 
Processing UV image 0520 ... 
Processing UV image 0530 ... 
Processing UV image 0540 ... 
Processing UV image 0550 ... 
Processing UV image 0560 ... 
Processing UV image 0570 ... 
Processing UV image 0580 ... 
Processing UV image 0590 ... 
Processing UV image 0600 ... 
Processing UV image 0610 ... 
Processing UV image 0620 ... 
Processing UV image 0630 ... 
Processing UV image 0640 ... 
Processing UV image 0650 ... 
Processing UV image 0660 ... 
Processing UV image 0670 ... 
Processing UV image 0680 ... 
Processing UV image 0690 ... 
Processing UV image 0700 ... 
Saving specimen R66 ROI3 in matlab form ...
Warning: Variable 'surface_masks' cannot be saved to a MAT-file whose version is older than 7.3.
To save this variable, use the -v7.3 switch.
Skipping... 
> In Make_MillData_Highres_Cortical at 259
  In make_cortical_uv_binary_Unloaded at 29
  In Run_Selected_Functions1 at 5
Elapsed time is 3534.904143 seconds.

spec_name =

69

Error in ==> RTL06_RegionOfInterest_Cortical at 3
if strcmp(spec_name , '53') && strcmp(ROI , 'ROI1')

??? Output argument "start_slice" (and maybe others) not assigned during call to "\\Biomech-10\i\MatlabCode\Cortical\RTL06_RegionOfInterest_Cortical.m>RTL06_RegionOfInterest_Cortical".

Error in ==> Make_MillData_Highres_Cortical at 8
[start_slice, end_slice] = RTL06_RegionOfInterest_Cortical(spec_name, ROI) ;

Error in ==> make_cortical_uv_binary_Unloaded at 29
        Make_MillData_Highres_Cortical(spec_name, inputDrive1, inputDrive2, saveDrive, roi);%%%%

Error in ==> Run_Selected_Functions1 at 5
make_cortical_uv_binary_Unloaded();
 
%}

