function BoneStats_Script_Cortical(specimen_number)

%specimen_number = { '53', '54', '57', '58', '62', '65', '70', '71'};
%specimen_number = { '53', '54', '57', '58', '70', '71'}; %do 62 and 65 after Erin looks at the CA thresholding
%R55 missing thresh_FITC_3dclosed
%R58 missing ROIs
%R66 non-loaded specimen; not in Biomech-11/n anymore
%specimen_number = { '54'};

%1 corresponds with the endosteal surface
%2 corresponds with the periosteal surface

voxel_width = 2.75; %voxel width in microns
voxel_height = 2.75; %voxel height in microns
voxel_depth = 5.00; %voxel depth in microns
area_scale = 1000000; %for conversion from microns^2 to (mm)^2
vol_scale = 1000000000; %for conversion from microns^3 to (mm)^3

L = length(specimen_number);
num_regs = 3; %number of ROIs
num_cols = 12; %number of columns
BoneStats = cell(2*(num_regs + 1) + 1, num_cols); %4 for 3 ROIs and 1 header row, +1 for space in between endo and periosteal data

headers = {'Specimen', 'ROI', 'MS((mm)^2)', 'BS((mm)^2)', 'MS/BS', 'BV((mm)^3)', ...
    'BFV((mm)^3)', 'Ct.Ar((mm)^2)', 'Tt.Ar((mm)^2)', 'Ct.Ar/Tt.Ar', 'Ct.Th(um)', 'MAR(um/day)'};
% MS = 'Mineralizing Surface' of this ROI((mm)^2)
% BS = 'Bone Surface' of this ROI((mm)^2)
% MS/BS = 'Mineralizing Surface / Bone Surface' for this ROI(unitless)
% BV = 'Bone Volume' of this ROI((mm)^3)
% BFV = 'Bone Formation Volume' of this ROI((mm)^3)
% Ct.Ar = Average 'Cortical Cross Sectional Area' for this ROI ((mm)^2)
% Tt.Ar = Average 'Total Cross Sectional Area' for this ROI ((mm)^2)
% Ct.Ar / Tt.Ar = Average 'Cortical Cross Sectional Area' per Total Cross Sectional Area' for this ROI (unitless)
% Ct.Th = Average 'Cortical Thickness' for this ROI (microns)
% MAR = Average 'Mineral Apposition Rate' for this ROI (microns per day)

for j = 1:num_cols
    BoneStats{1, j} = headers{j};
    BoneStats{num_regs + 3, j} = headers{j};
end


%inputDrive1 = '\\Biomech-11\n' ; %bfv images & inner masks
%inputDrive2 = '\\Biomech-10\i'; %UV Cortical Shells and Full Cortical Shell masks
saveDrive = '\\Biomech-10\i'; %output drive for MSBS_ROI#s

for i = 1:L
    spec_name = specimen_number{i};
    display(spec_name) %%%%
    specimen = ['RTL06_R' spec_name '_C8_Processed'];
    for j = 1:num_regs
    %for j = 3:num_regs
        %j = 1 for ROI1
        %j = 2; %for ROI2 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %j = 3; %for ROI3
        %ROI3 is the region after ROI1 and before ROI2, not after ROI2
        roi = ['ROI', num2str(j)];
        
        tic
        
        message = ['Loading binary images for specimen R', spec_name, ' ', roi, ' ...\n'];
        fprintf(message);
        
        %Call this function if any changes are made to how the binary images are loaded and pre-processed:
        %[bw_BFV_img, bw_UV_img, inner_mask_img, bw_UV_holes, CS_filled, surface_masks, start_slice, end_slice] = Make_MillData_Highres_Cortical(spec_name, inputDrive1, inputDrive2, saveDrive, roi);
        %Otherwise, just load the already processed data from the saved Matlab form:
        path = ['\\Biomech-10\i\RTL06_Cortical_Processed\RTL06_R', spec_name, '_C8_Processed\Tiled\MillDataBinary_', roi, '.mat'];
        load(path);
        
        %Find starting and ending indices of current ROI
        [start_slice, end_slice] = RTL06_RegionOfInterest_Cortical(spec_name, roi);
        
        savDir = [saveDrive '\RTL06_Cortical_Processed\' specimen '\Tiled\']; %output directory
        if isdir(savDir)==0; mkdir(savDir); end
        
        %Process the binary images to retrieve useful data
        message = ['Processing binary images of specimen R', spec_name, ' ', roi, ' to retrieve data ...\n'];
        fprintf(message);
        tic
        %MSBS_matrix_input_Cortical(...) returns 5 2x1 matrices
        [mineralizing_surface, bone_surface, formation_volume, Ct_Th, MAR] = MSBS_matrix_input_Cortical(bw_UV_img, bw_BFV_img, inner_mask_img, bw_UV_holes, surface_masks, savDir, start_slice, end_slice, spec_name, roi);
        toc
        
        BoneStats{j+1,1} = ['R', spec_name, ' Endosteal'];
        BoneStats{j+6,1} = ['R', spec_name, ' Periosteal'];
        BoneStats{j+1,2} = num2str(j); %Region of Interest
        BoneStats{j+6,2} = num2str(j); %Region of Interest
        BoneStats{j+1,3} = (mineralizing_surface(1) * (voxel_height*voxel_depth)) / area_scale; %Mineralizing Surface
        BoneStats{j+6,3} = (mineralizing_surface(2) * (voxel_height*voxel_depth)) / area_scale; %Mineralizing Surface
        BoneStats{j+1,4} = (bone_surface(1) * (voxel_height*voxel_depth)) / area_scale; %Bone Surface
        BoneStats{j+6,4} = (bone_surface(2) * (voxel_height*voxel_depth)) / area_scale; %Bone Surface
        BoneStats{j+1,5} = mineralizing_surface(1)./bone_surface(1);
        BoneStats{j+6,5} = mineralizing_surface(2)./bone_surface(2);
        
        BV = sum(sum(sum(bw_UV_holes)));
        BoneStats{j+1,6} = (BV * (voxel_width*voxel_height*voxel_depth)) / vol_scale; %bone Volume
        BoneStats{j+6,6} = (BV * (voxel_width*voxel_height*voxel_depth)) / vol_scale; %bone Volume
        
        FV = formation_volume(1);
        BoneStats{j+1,7} = (FV * (voxel_width*voxel_height*voxel_depth)) / vol_scale; %Bone Formation Volume
        FV = formation_volume(2);
        BoneStats{j+6,7} = (FV * (voxel_width*voxel_height*voxel_depth)) / vol_scale; %Bone Formation Volume
        
        Ct_Ar = sum(sum(sum(bw_UV_holes))) / (end_slice - start_slice + 1); %Average Cortical Cross Sectional Area
        BoneStats{j + 1, 8} = (Ct_Ar * (voxel_height*voxel_width)) / area_scale; %Average Cortical Thickness
        BoneStats{j + 6, 8} = (Ct_Ar * (voxel_height*voxel_width)) / area_scale; %Average Cortical Thickness
        Tt_Ar = sum(sum(sum(CS_filled))) / (end_slice - start_slice + 1); %Average total cross sectional area
        BoneStats{j + 1, 9} = (Tt_Ar * (voxel_height*voxel_width)) / area_scale; %Average total vertebral cross sectional area
        BoneStats{j + 6, 9} = (Tt_Ar * (voxel_height*voxel_width)) / area_scale; %Average total vertebral cross sectional area
        BoneStats{j + 1, 10} = Ct_Ar / Tt_Ar; %Average cortical area divided by total vertebral cross sectional area
        BoneStats{j + 6, 10} = Ct_Ar / Tt_Ar; %Average cortical area divided by total vertebral cross sectional area
        BoneStats{j+1,11} = Ct_Th * voxel_width; %Average Cortical Thickness
        BoneStats{j+6,11} = Ct_Th * voxel_width; %Average Cortical Thickness
        BoneStats{j+1,12} = MAR(1) * voxel_width; %Average MAR (mineral apposition rate)
        BoneStats{j+6,12} = MAR(2) * voxel_width; %Average MAR (mineral apposition rate)
        
        clear bw_BFV_img  bw_BFV_img inner_mask_img mineralizing_surface bone_surface formation_volume %%%%
        toc
    end
    
    filename = [saveDrive, '\RTL06_Cortical_Processed\RTL06_R' spec_name, '_C8_Processed\Tiled\R', spec_name, '_C8_BoneStats.xls'];
    xlswrite(filename, BoneStats(:,:));
end

%Test Run #1 (samples R53,54,57,62,65,70,71)
%{

spec_name =

53

Processing R53 ROI3 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0520 ... 
Processing UV image 0530 ... 
Processing UV image 0540 ... 
Processing UV image 0550 ... 
Processing UV image 0560 ... 
Processing UV image 0570 ... 
Processing UV image 0580 ... 
Processing UV image 0590 ... 
Processing UV image 0600 ... 
Processing UV image 0610 ... 
Processing UV image 0620 ... 
Processing UV image 0630 ... 
Processing UV image 0640 ... 
Processing UV image 0650 ... 
Processing UV image 0660 ... 
Processing UV image 0670 ... 
Processing UV image 0680 ... 
Processing UV image 0690 ... 
Processing UV image 0700 ... 
Processing UV image 0710 ... 
Processing UV image 0720 ... 
Processing UV image 0730 ... 
Processing UV image 0740 ... 
Processing UV image 0750 ... 
Processing UV image 0760 ... 
Saving specimen R53 ROI3 in matlab form ...
Elapsed time is 1553.565293 seconds.

spec_name =

53

Loading binary images for specimen R53 ROI3 ...
Processing binary images of specimen R53 ROI3 to retrieve data ...
Calculating MAR for specimen R53 ROI3 ...
Creating masked edges and calculating Ct.Th for R53 ROI3 ...
Creating masked edge and calculating Ct.Th for slice 0520 ...
Creating masked edge and calculating Ct.Th for slice 0530 ...
Creating masked edge and calculating Ct.Th for slice 0540 ...
Creating masked edge and calculating Ct.Th for slice 0550 ...
Creating masked edge and calculating Ct.Th for slice 0560 ...
Creating masked edge and calculating Ct.Th for slice 0570 ...
Creating masked edge and calculating Ct.Th for slice 0580 ...
Creating masked edge and calculating Ct.Th for slice 0590 ...
Creating masked edge and calculating Ct.Th for slice 0600 ...
Creating masked edge and calculating Ct.Th for slice 0610 ...
Creating masked edge and calculating Ct.Th for slice 0620 ...
Creating masked edge and calculating Ct.Th for slice 0630 ...
Creating masked edge and calculating Ct.Th for slice 0640 ...
Creating masked edge and calculating Ct.Th for slice 0650 ...
Creating masked edge and calculating Ct.Th for slice 0660 ...
Creating masked edge and calculating Ct.Th for slice 0670 ...
Creating masked edge and calculating Ct.Th for slice 0680 ...
Creating masked edge and calculating Ct.Th for slice 0690 ...
Creating masked edge and calculating Ct.Th for slice 0700 ...
Creating masked edge and calculating Ct.Th for slice 0710 ...
Creating masked edge and calculating Ct.Th for slice 0720 ...
Creating masked edge and calculating Ct.Th for slice 0730 ...
Creating masked edge and calculating Ct.Th for slice 0740 ...
Creating masked edge and calculating Ct.Th for slice 0750 ...
Creating masked edge and calculating Ct.Th for slice 0760 ...
Calculating bone_surface for R53 ROI3 ...
Calculating mineralizing_surface for R53 ROI3 ...
Writing MSBS_ROI3 images...
Calculating formation_volume for R53 ROI3 ...
Elapsed time is 905.564137 seconds.
Elapsed time is 906.538634 seconds.

spec_name =

53

Processing R53 ROI1 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0260 ... 
Processing UV image 0270 ... 
Processing UV image 0280 ... 
Processing UV image 0290 ... 
Processing UV image 0300 ... 
Processing UV image 0310 ... 
Processing UV image 0320 ... 
Processing UV image 0330 ... 
Processing UV image 0340 ... 
Processing UV image 0350 ... 
Processing UV image 0360 ... 
Processing UV image 0370 ... 
Processing UV image 0380 ... 
Processing UV image 0390 ... 
Processing UV image 0400 ... 
Processing UV image 0410 ... 
Processing UV image 0420 ... 
Processing UV image 0430 ... 
Processing UV image 0440 ... 
Processing UV image 0450 ... 
Processing UV image 0460 ... 
Processing UV image 0470 ... 
Processing UV image 0480 ... 
Processing UV image 0490 ... 
Processing UV image 0500 ... 
Processing UV image 0510 ... 
Saving specimen R53 ROI1 in matlab form ...
Elapsed time is 1617.769010 seconds.
Processing R53 ROI2 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0770 ... 
Processing UV image 0780 ... 
Processing UV image 0790 ... 
Processing UV image 0800 ... 
Processing UV image 0810 ... 
Processing UV image 0820 ... 
Processing UV image 0830 ... 
Processing UV image 0840 ... 
Processing UV image 0850 ... 
Processing UV image 0860 ... 
Processing UV image 0870 ... 
Processing UV image 0880 ... 
Processing UV image 0890 ... 
Processing UV image 0900 ... 
Processing UV image 0910 ... 
Processing UV image 0920 ... 
Processing UV image 0930 ... 
Processing UV image 0940 ... 
Processing UV image 0950 ... 
Processing UV image 0960 ... 
Processing UV image 0970 ... 
Processing UV image 0980 ... 
Processing UV image 0990 ... 
Processing UV image 1000 ... 
Processing UV image 1010 ... 
Processing UV image 1020 ... 
Saving specimen R53 ROI2 in matlab form ...
Elapsed time is 1596.325009 seconds.
Processing R53 ROI3 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0520 ... 
Processing UV image 0530 ... 
Processing UV image 0540 ... 
Processing UV image 0550 ... 
Processing UV image 0560 ... 
Processing UV image 0570 ... 
Processing UV image 0580 ... 
Processing UV image 0590 ... 
Processing UV image 0600 ... 
Processing UV image 0610 ... 
Processing UV image 0620 ... 
Processing UV image 0630 ... 
Processing UV image 0640 ... 
Processing UV image 0650 ... 
Processing UV image 0660 ... 
Processing UV image 0670 ... 
Processing UV image 0680 ... 
Processing UV image 0690 ... 
Processing UV image 0700 ... 
Processing UV image 0710 ... 
Processing UV image 0720 ... 
Processing UV image 0730 ... 
Processing UV image 0740 ... 
Processing UV image 0750 ... 
Processing UV image 0760 ... 
Saving specimen R53 ROI3 in matlab form ...
Elapsed time is 1484.027831 seconds.

spec_name =

54

Processing R54 ROI1 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0190 ... 
Processing UV image 0200 ... 
Processing UV image 0210 ... 
Processing UV image 0220 ... 
Processing UV image 0230 ... 
Processing UV image 0240 ... 
Processing UV image 0250 ... 
Processing UV image 0260 ... 
Processing UV image 0270 ... 
Processing UV image 0280 ... 
Processing UV image 0290 ... 
Processing UV image 0300 ... 
Processing UV image 0310 ... 
Processing UV image 0320 ... 
Processing UV image 0330 ... 
Processing UV image 0340 ... 
Processing UV image 0350 ... 
Processing UV image 0360 ... 
Processing UV image 0370 ... 
Processing UV image 0380 ... 
Processing UV image 0390 ... 
Processing UV image 0400 ... 
Processing UV image 0410 ... 
Processing UV image 0420 ... 
Processing UV image 0430 ... 
Processing UV image 0440 ... 
Saving specimen R54 ROI1 in matlab form ...
Elapsed time is 1570.241442 seconds.
Processing R54 ROI2 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0690 ... 
Processing UV image 0700 ... 
Processing UV image 0710 ... 
Processing UV image 0720 ... 
Processing UV image 0730 ... 
Processing UV image 0740 ... 
Processing UV image 0750 ... 
Processing UV image 0760 ... 
Processing UV image 0770 ... 
Processing UV image 0780 ... 
Processing UV image 0790 ... 
Processing UV image 0800 ... 
Processing UV image 0810 ... 
Processing UV image 0820 ... 
Processing UV image 0830 ... 
Processing UV image 0840 ... 
Processing UV image 0850 ... 
Processing UV image 0860 ... 
Processing UV image 0870 ... 
Processing UV image 0880 ... 
Processing UV image 0890 ... 
Processing UV image 0900 ... 
Processing UV image 0910 ... 
Processing UV image 0920 ... 
Processing UV image 0930 ... 
Processing UV image 0940 ... 
Saving specimen R54 ROI2 in matlab form ...
Elapsed time is 1548.123517 seconds.
Processing R54 ROI3 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0450 ... 
Processing UV image 0460 ... 
Processing UV image 0470 ... 
Processing UV image 0480 ... 
Processing UV image 0490 ... 
Processing UV image 0500 ... 
Processing UV image 0510 ... 
Processing UV image 0520 ... 
Processing UV image 0530 ... 
Processing UV image 0540 ... 
Processing UV image 0550 ... 
Processing UV image 0560 ... 
Processing UV image 0570 ... 
Processing UV image 0580 ... 
Processing UV image 0590 ... 
Processing UV image 0600 ... 
Processing UV image 0610 ... 
Processing UV image 0620 ... 
Processing UV image 0630 ... 
Processing UV image 0640 ... 
Processing UV image 0650 ... 
Processing UV image 0660 ... 
Processing UV image 0670 ... 
Processing UV image 0680 ... 
Saving specimen R54 ROI3 in matlab form ...
Elapsed time is 1495.269901 seconds.

spec_name =

57

Processing R57 ROI1 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0150 ... 
Processing UV image 0160 ... 
Processing UV image 0170 ... 
Processing UV image 0180 ... 
Processing UV image 0190 ... 
Processing UV image 0200 ... 
Processing UV image 0210 ... 
Processing UV image 0220 ... 
Processing UV image 0230 ... 
Processing UV image 0240 ... 
Processing UV image 0250 ... 
Processing UV image 0260 ... 
Processing UV image 0270 ... 
Processing UV image 0280 ... 
Processing UV image 0290 ... 
Processing UV image 0300 ... 
Processing UV image 0310 ... 
Processing UV image 0320 ... 
Processing UV image 0330 ... 
Processing UV image 0340 ... 
Processing UV image 0350 ... 
Processing UV image 0360 ... 
Processing UV image 0370 ... 
Processing UV image 0380 ... 
Processing UV image 0390 ... 
Processing UV image 0400 ... 
Saving specimen R57 ROI1 in matlab form ...
Elapsed time is 1461.719122 seconds.
Processing R57 ROI2 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0660 ... 
Processing UV image 0670 ... 
Processing UV image 0680 ... 
Processing UV image 0690 ... 
Processing UV image 0700 ... 
Processing UV image 0710 ... 
Processing UV image 0720 ... 
Processing UV image 0730 ... 
Processing UV image 0740 ... 
Processing UV image 0750 ... 
Processing UV image 0760 ... 
Processing UV image 0770 ... 
Processing UV image 0780 ... 
Processing UV image 0790 ... 
Processing UV image 0800 ... 
Processing UV image 0810 ... 
Processing UV image 0820 ... 
Processing UV image 0830 ... 
Processing UV image 0840 ... 
Processing UV image 0850 ... 
Processing UV image 0860 ... 
Processing UV image 0870 ... 
Processing UV image 0880 ... 
Processing UV image 0890 ... 
Processing UV image 0900 ... 
Processing UV image 0910 ... 
Saving specimen R57 ROI2 in matlab form ...
Elapsed time is 1457.653492 seconds.
Processing R57 ROI3 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0410 ... 
Processing UV image 0420 ... 
Processing UV image 0430 ... 
Processing UV image 0440 ... 
Processing UV image 0450 ... 
Processing UV image 0460 ... 
Processing UV image 0470 ... 
Processing UV image 0480 ... 
Processing UV image 0490 ... 
Processing UV image 0500 ... 
Processing UV image 0510 ... 
Processing UV image 0520 ... 
Processing UV image 0530 ... 
Processing UV image 0540 ... 
Processing UV image 0550 ... 
Processing UV image 0560 ... 
Processing UV image 0570 ... 
Processing UV image 0580 ... 
Processing UV image 0590 ... 
Processing UV image 0600 ... 
Processing UV image 0610 ... 
Processing UV image 0620 ... 
Processing UV image 0630 ... 
Processing UV image 0640 ... 
Processing UV image 0650 ... 
Saving specimen R57 ROI3 in matlab form ...
Elapsed time is 1397.202710 seconds.

spec_name =

62

Processing R62 ROI1 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0140 ... 
Processing UV image 0150 ... 
Processing UV image 0160 ... 
Processing UV image 0170 ... 
Processing UV image 0180 ... 
Processing UV image 0190 ... 
Processing UV image 0200 ... 
Processing UV image 0210 ... 
Processing UV image 0220 ... 
Processing UV image 0230 ... 
Processing UV image 0240 ... 
Processing UV image 0250 ... 
Processing UV image 0260 ... 
Processing UV image 0270 ... 
Processing UV image 0280 ... 
Processing UV image 0290 ... 
Processing UV image 0300 ... 
Processing UV image 0310 ... 
Processing UV image 0320 ... 
Processing UV image 0330 ... 
Processing UV image 0340 ... 
Processing UV image 0350 ... 
Processing UV image 0360 ... 
Processing UV image 0370 ... 
Processing UV image 0380 ... 
Processing UV image 0390 ... 
Saving specimen R62 ROI1 in matlab form ...
Elapsed time is 1317.454020 seconds.
Processing R62 ROI2 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0680 ... 
Processing UV image 0690 ... 
Processing UV image 0700 ... 
Processing UV image 0710 ... 
Processing UV image 0720 ... 
Processing UV image 0730 ... 
Processing UV image 0740 ... 
Processing UV image 0750 ... 
Processing UV image 0760 ... 
Processing UV image 0770 ... 
Processing UV image 0780 ... 
Processing UV image 0790 ... 
Processing UV image 0800 ... 
Processing UV image 0810 ... 
Processing UV image 0820 ... 
Processing UV image 0830 ... 
Processing UV image 0840 ... 
Processing UV image 0850 ... 
Processing UV image 0860 ... 
Processing UV image 0870 ... 
Processing UV image 0880 ... 
Processing UV image 0890 ... 
Processing UV image 0900 ... 
Processing UV image 0910 ... 
Processing UV image 0920 ... 
Processing UV image 0930 ... 
Saving specimen R62 ROI2 in matlab form ...
Elapsed time is 1326.022080 seconds.
Processing R62 ROI3 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0400 ... 
Processing UV image 0410 ... 
Processing UV image 0420 ... 
Processing UV image 0430 ... 
Processing UV image 0440 ... 
Processing UV image 0450 ... 
Processing UV image 0460 ... 
Processing UV image 0470 ... 
Processing UV image 0480 ... 
Processing UV image 0490 ... 
Processing UV image 0500 ... 
Processing UV image 0510 ... 
Processing UV image 0520 ... 
Processing UV image 0530 ... 
Processing UV image 0540 ... 
Processing UV image 0550 ... 
Processing UV image 0560 ... 
Processing UV image 0570 ... 
Processing UV image 0580 ... 
Processing UV image 0590 ... 
Processing UV image 0600 ... 
Processing UV image 0610 ... 
Processing UV image 0620 ... 
Processing UV image 0630 ... 
Processing UV image 0640 ... 
Processing UV image 0650 ... 
Processing UV image 0660 ... 
Processing UV image 0670 ... 
Saving specimen R62 ROI3 in matlab form ...
Elapsed time is 1428.076240 seconds.

spec_name =

65

Processing R65 ROI1 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0140 ... 
Processing UV image 0150 ... 
Processing UV image 0160 ... 
Processing UV image 0170 ... 
Processing UV image 0180 ... 
Processing UV image 0190 ... 
Processing UV image 0200 ... 
Processing UV image 0210 ... 
Processing UV image 0220 ... 
Processing UV image 0230 ... 
Processing UV image 0240 ... 
Processing UV image 0250 ... 
Processing UV image 0260 ... 
Processing UV image 0270 ... 
Processing UV image 0280 ... 
Processing UV image 0290 ... 
Processing UV image 0300 ... 
Processing UV image 0310 ... 
Processing UV image 0320 ... 
Processing UV image 0330 ... 
Processing UV image 0340 ... 
Processing UV image 0350 ... 
Processing UV image 0360 ... 
Processing UV image 0370 ... 
Processing UV image 0380 ... 
Processing UV image 0390 ... 
Saving specimen R65 ROI1 in matlab form ...
Elapsed time is 1406.833696 seconds.
Processing R65 ROI2 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0670 ... 
Processing UV image 0680 ... 
Processing UV image 0690 ... 
Processing UV image 0700 ... 
Processing UV image 0710 ... 
Processing UV image 0720 ... 
Processing UV image 0730 ... 
Processing UV image 0740 ... 
Processing UV image 0750 ... 
Processing UV image 0760 ... 
Processing UV image 0770 ... 
Processing UV image 0780 ... 
Processing UV image 0790 ... 
Processing UV image 0800 ... 
Processing UV image 0810 ... 
Processing UV image 0820 ... 
Processing UV image 0830 ... 
Processing UV image 0840 ... 
Processing UV image 0850 ... 
Processing UV image 0860 ... 
Processing UV image 0870 ... 
Processing UV image 0880 ... 
Processing UV image 0890 ... 
Processing UV image 0900 ... 
Processing UV image 0910 ... 
Processing UV image 0920 ... 
Saving specimen R65 ROI2 in matlab form ...
Elapsed time is 1390.870304 seconds.
Processing R65 ROI3 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0400 ... 
Processing UV image 0410 ... 
Processing UV image 0420 ... 
Processing UV image 0430 ... 
Processing UV image 0440 ... 
Processing UV image 0450 ... 
Processing UV image 0460 ... 
Processing UV image 0470 ... 
Processing UV image 0480 ... 
Processing UV image 0490 ... 
Processing UV image 0500 ... 
Processing UV image 0510 ... 
Processing UV image 0520 ... 
Processing UV image 0530 ... 
Processing UV image 0540 ... 
Processing UV image 0550 ... 
Processing UV image 0560 ... 
Processing UV image 0570 ... 
Processing UV image 0580 ... 
Processing UV image 0590 ... 
Processing UV image 0600 ... 
Processing UV image 0610 ... 
Processing UV image 0620 ... 
Processing UV image 0630 ... 
Processing UV image 0640 ... 
Processing UV image 0650 ... 
Processing UV image 0660 ... 
Saving specimen R65 ROI3 in matlab form ...
Elapsed time is 1436.253758 seconds.

spec_name =

70

Processing R70 ROI1 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0160 ... 
Processing UV image 0170 ... 
Processing UV image 0180 ... 
Processing UV image 0190 ... 
Processing UV image 0200 ... 
Processing UV image 0210 ... 
Processing UV image 0220 ... 
Processing UV image 0230 ... 
Processing UV image 0240 ... 
Processing UV image 0250 ... 
Processing UV image 0260 ... 
Processing UV image 0270 ... 
Processing UV image 0280 ... 
Processing UV image 0290 ... 
Processing UV image 0300 ... 
Processing UV image 0310 ... 
Processing UV image 0320 ... 
Processing UV image 0330 ... 
Processing UV image 0340 ... 
Processing UV image 0350 ... 
Processing UV image 0360 ... 
Processing UV image 0370 ... 
Processing UV image 0380 ... 
Processing UV image 0390 ... 
Processing UV image 0400 ... 
Processing UV image 0410 ... 
Saving specimen R70 ROI1 in matlab form ...
Elapsed time is 1340.639432 seconds.
Processing R70 ROI2 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0660 ... 
Processing UV image 0670 ... 
Processing UV image 0680 ... 
Processing UV image 0690 ... 
Processing UV image 0700 ... 
Processing UV image 0710 ... 
Processing UV image 0720 ... 
Processing UV image 0730 ... 
Processing UV image 0740 ... 
Processing UV image 0750 ... 
Processing UV image 0760 ... 
Processing UV image 0770 ... 
Processing UV image 0780 ... 
Processing UV image 0790 ... 
Processing UV image 0800 ... 
Processing UV image 0810 ... 
Processing UV image 0820 ... 
Processing UV image 0830 ... 
Processing UV image 0840 ... 
Processing UV image 0850 ... 
Processing UV image 0860 ... 
Processing UV image 0870 ... 
Processing UV image 0880 ... 
Processing UV image 0890 ... 
Processing UV image 0900 ... 
Processing UV image 0910 ... 
Saving specimen R70 ROI2 in matlab form ...
Elapsed time is 1324.465104 seconds.
Processing R70 ROI3 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0420 ... 
Processing UV image 0430 ... 
Processing UV image 0440 ... 
Processing UV image 0450 ... 
Processing UV image 0460 ... 
Processing UV image 0470 ... 
Processing UV image 0480 ... 
Processing UV image 0490 ... 
Processing UV image 0500 ... 
Processing UV image 0510 ... 
Processing UV image 0520 ... 
Processing UV image 0530 ... 
Processing UV image 0540 ... 
Processing UV image 0550 ... 
Processing UV image 0560 ... 
Processing UV image 0570 ... 
Processing UV image 0580 ... 
Processing UV image 0590 ... 
Processing UV image 0600 ... 
Processing UV image 0610 ... 
Processing UV image 0620 ... 
Processing UV image 0630 ... 
Processing UV image 0640 ... 
Processing UV image 0650 ... 
Saving specimen R70 ROI3 in matlab form ...
Elapsed time is 1208.489710 seconds.

spec_name =

71

Processing R71 ROI1 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0220 ... 
Processing UV image 0230 ... 
Processing UV image 0240 ... 
Processing UV image 0250 ... 
Processing UV image 0260 ... 
Processing UV image 0270 ... 
Processing UV image 0280 ... 
Processing UV image 0290 ... 
Processing UV image 0300 ... 
Processing UV image 0310 ... 
Processing UV image 0320 ... 
Processing UV image 0330 ... 
Processing UV image 0340 ... 
Processing UV image 0350 ... 
Processing UV image 0360 ... 
Processing UV image 0370 ... 
Processing UV image 0380 ... 
Processing UV image 0390 ... 
Processing UV image 0400 ... 
Processing UV image 0410 ... 
Processing UV image 0420 ... 
Processing UV image 0430 ... 
Processing UV image 0440 ... 
Processing UV image 0450 ... 
Processing UV image 0460 ... 
Processing UV image 0470 ... 
Saving specimen R71 ROI1 in matlab form ...
Elapsed time is 1228.687958 seconds.
Processing R71 ROI2 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0720 ... 
Processing UV image 0730 ... 
Processing UV image 0740 ... 
Processing UV image 0750 ... 
Processing UV image 0760 ... 
Processing UV image 0770 ... 
Processing UV image 0780 ... 
Processing UV image 0790 ... 
Processing UV image 0800 ... 
Processing UV image 0810 ... 
Processing UV image 0820 ... 
Processing UV image 0830 ... 
Processing UV image 0840 ... 
Processing UV image 0850 ... 
Processing UV image 0860 ... 
Processing UV image 0870 ... 
Processing UV image 0880 ... 
Processing UV image 0890 ... 
Processing UV image 0900 ... 
Processing UV image 0910 ... 
Processing UV image 0920 ... 
Processing UV image 0930 ... 
Processing UV image 0940 ... 
Processing UV image 0950 ... 
Processing UV image 0960 ... 
Processing UV image 0970 ... 
Saving specimen R71 ROI2 in matlab form ...
Elapsed time is 1218.450811 seconds.
Processing R71 ROI3 ...
Loading Calcein images ...
Loading inner masks ...
Loading UV and thresholded images and storing as cleaned masks ...
... AND creating endosteal and periosteal surface masks ...
Processing UV image 0480 ... 
Processing UV image 0490 ... 
Processing UV image 0500 ... 
Processing UV image 0510 ... 
Processing UV image 0520 ... 
Processing UV image 0530 ... 
Processing UV image 0540 ... 
Processing UV image 0550 ... 
Processing UV image 0560 ... 
Processing UV image 0570 ... 
Processing UV image 0580 ... 
Processing UV image 0590 ... 
Processing UV image 0600 ... 
Processing UV image 0610 ... 
Processing UV image 0620 ... 
Processing UV image 0630 ... 
Processing UV image 0640 ... 
Processing UV image 0650 ... 
Processing UV image 0660 ... 
Processing UV image 0670 ... 
Processing UV image 0680 ... 
Processing UV image 0690 ... 
Processing UV image 0700 ... 
Processing UV image 0710 ... 
Saving specimen R71 ROI3 in matlab form ...
Elapsed time is 1131.234573 seconds.

spec_name =

53

Loading binary images for specimen R53 ROI1 ...
Processing binary images of specimen R53 ROI1 to retrieve data ...
Calculating MAR for specimen R53 ROI1 ...
Creating masked edges and calculating Ct.Th for R53 ROI1 ...
Creating masked edge and calculating Ct.Th for slice 0260 ...
Creating masked edge and calculating Ct.Th for slice 0270 ...
Creating masked edge and calculating Ct.Th for slice 0280 ...
Creating masked edge and calculating Ct.Th for slice 0290 ...
Creating masked edge and calculating Ct.Th for slice 0300 ...
Creating masked edge and calculating Ct.Th for slice 0310 ...
Creating masked edge and calculating Ct.Th for slice 0320 ...
Creating masked edge and calculating Ct.Th for slice 0330 ...
Creating masked edge and calculating Ct.Th for slice 0340 ...
Creating masked edge and calculating Ct.Th for slice 0350 ...
Creating masked edge and calculating Ct.Th for slice 0360 ...
Creating masked edge and calculating Ct.Th for slice 0370 ...
Creating masked edge and calculating Ct.Th for slice 0380 ...
Creating masked edge and calculating Ct.Th for slice 0390 ...
Creating masked edge and calculating Ct.Th for slice 0400 ...
Creating masked edge and calculating Ct.Th for slice 0410 ...
Creating masked edge and calculating Ct.Th for slice 0420 ...
Creating masked edge and calculating Ct.Th for slice 0430 ...
Creating masked edge and calculating Ct.Th for slice 0440 ...
Creating masked edge and calculating Ct.Th for slice 0450 ...
Creating masked edge and calculating Ct.Th for slice 0460 ...
Creating masked edge and calculating Ct.Th for slice 0470 ...
Creating masked edge and calculating Ct.Th for slice 0480 ...
Creating masked edge and calculating Ct.Th for slice 0490 ...
Creating masked edge and calculating Ct.Th for slice 0500 ...
Creating masked edge and calculating Ct.Th for slice 0510 ...
Calculating bone_surface for R53 ROI1 ...
Calculating mineralizing_surface for R53 ROI1 ...
Writing MSBS_ROI1 images...
Calculating formation_volume for R53 ROI1 ...
Elapsed time is 924.315127 seconds.
Elapsed time is 925.289108 seconds.
Loading binary images for specimen R53 ROI2 ...
Processing binary images of specimen R53 ROI2 to retrieve data ...
Calculating MAR for specimen R53 ROI2 ...
Creating masked edges and calculating Ct.Th for R53 ROI2 ...
Creating masked edge and calculating Ct.Th for slice 0779 ...
Creating masked edge and calculating Ct.Th for slice 0789 ...
Creating masked edge and calculating Ct.Th for slice 0799 ...
Creating masked edge and calculating Ct.Th for slice 0809 ...
Creating masked edge and calculating Ct.Th for slice 0819 ...
Creating masked edge and calculating Ct.Th for slice 0829 ...
Creating masked edge and calculating Ct.Th for slice 0839 ...
Creating masked edge and calculating Ct.Th for slice 0849 ...
Creating masked edge and calculating Ct.Th for slice 0859 ...
Creating masked edge and calculating Ct.Th for slice 0869 ...
Creating masked edge and calculating Ct.Th for slice 0879 ...
Creating masked edge and calculating Ct.Th for slice 0889 ...
Creating masked edge and calculating Ct.Th for slice 0899 ...
Creating masked edge and calculating Ct.Th for slice 0909 ...
Creating masked edge and calculating Ct.Th for slice 0919 ...
Creating masked edge and calculating Ct.Th for slice 0929 ...
Creating masked edge and calculating Ct.Th for slice 0939 ...
Creating masked edge and calculating Ct.Th for slice 0949 ...
Creating masked edge and calculating Ct.Th for slice 0959 ...
Creating masked edge and calculating Ct.Th for slice 0969 ...
Creating masked edge and calculating Ct.Th for slice 0979 ...
Creating masked edge and calculating Ct.Th for slice 0989 ...
Creating masked edge and calculating Ct.Th for slice 0999 ...
Creating masked edge and calculating Ct.Th for slice 1009 ...
Creating masked edge and calculating Ct.Th for slice 1019 ...
Creating masked edge and calculating Ct.Th for slice 1029 ...
Calculating bone_surface for R53 ROI2 ...
Calculating mineralizing_surface for R53 ROI2 ...
Writing MSBS_ROI2 images...
Calculating formation_volume for R53 ROI2 ...
Elapsed time is 922.557354 seconds.
Elapsed time is 923.434398 seconds.
Loading binary images for specimen R53 ROI3 ...
Processing binary images of specimen R53 ROI3 to retrieve data ...
Calculating MAR for specimen R53 ROI3 ...
Creating masked edges and calculating Ct.Th for R53 ROI3 ...
Creating masked edge and calculating Ct.Th for slice 0520 ...
Creating masked edge and calculating Ct.Th for slice 0530 ...
Creating masked edge and calculating Ct.Th for slice 0540 ...
Creating masked edge and calculating Ct.Th for slice 0550 ...
Creating masked edge and calculating Ct.Th for slice 0560 ...
Creating masked edge and calculating Ct.Th for slice 0570 ...
Creating masked edge and calculating Ct.Th for slice 0580 ...
Creating masked edge and calculating Ct.Th for slice 0590 ...
Creating masked edge and calculating Ct.Th for slice 0600 ...
Creating masked edge and calculating Ct.Th for slice 0610 ...
Creating masked edge and calculating Ct.Th for slice 0620 ...
Creating masked edge and calculating Ct.Th for slice 0630 ...
Creating masked edge and calculating Ct.Th for slice 0640 ...
Creating masked edge and calculating Ct.Th for slice 0650 ...
Creating masked edge and calculating Ct.Th for slice 0660 ...
Creating masked edge and calculating Ct.Th for slice 0670 ...
Creating masked edge and calculating Ct.Th for slice 0680 ...
Creating masked edge and calculating Ct.Th for slice 0690 ...
Creating masked edge and calculating Ct.Th for slice 0700 ...
Creating masked edge and calculating Ct.Th for slice 0710 ...
Creating masked edge and calculating Ct.Th for slice 0720 ...
Creating masked edge and calculating Ct.Th for slice 0730 ...
Creating masked edge and calculating Ct.Th for slice 0740 ...
Creating masked edge and calculating Ct.Th for slice 0750 ...
Creating masked edge and calculating Ct.Th for slice 0760 ...
Calculating bone_surface for R53 ROI3 ...
Calculating mineralizing_surface for R53 ROI3 ...
Writing MSBS_ROI3 images...
Calculating formation_volume for R53 ROI3 ...
Elapsed time is 906.516103 seconds.
Elapsed time is 907.548202 seconds.

spec_name =

54

Loading binary images for specimen R54 ROI1 ...
Processing binary images of specimen R54 ROI1 to retrieve data ...
Calculating MAR for specimen R54 ROI1 ...
Creating masked edges and calculating Ct.Th for R54 ROI1 ...
Creating masked edge and calculating Ct.Th for slice 0191 ...
Creating masked edge and calculating Ct.Th for slice 0201 ...
Creating masked edge and calculating Ct.Th for slice 0211 ...
Creating masked edge and calculating Ct.Th for slice 0221 ...
Creating masked edge and calculating Ct.Th for slice 0231 ...
Creating masked edge and calculating Ct.Th for slice 0241 ...
Creating masked edge and calculating Ct.Th for slice 0251 ...
Creating masked edge and calculating Ct.Th for slice 0261 ...
Creating masked edge and calculating Ct.Th for slice 0271 ...
Creating masked edge and calculating Ct.Th for slice 0281 ...
Creating masked edge and calculating Ct.Th for slice 0291 ...
Creating masked edge and calculating Ct.Th for slice 0301 ...
Creating masked edge and calculating Ct.Th for slice 0311 ...
Creating masked edge and calculating Ct.Th for slice 0321 ...
Creating masked edge and calculating Ct.Th for slice 0331 ...
Creating masked edge and calculating Ct.Th for slice 0341 ...
Creating masked edge and calculating Ct.Th for slice 0351 ...
Creating masked edge and calculating Ct.Th for slice 0361 ...
Creating masked edge and calculating Ct.Th for slice 0371 ...
Creating masked edge and calculating Ct.Th for slice 0381 ...
Creating masked edge and calculating Ct.Th for slice 0391 ...
Creating masked edge and calculating Ct.Th for slice 0401 ...
Creating masked edge and calculating Ct.Th for slice 0411 ...
Creating masked edge and calculating Ct.Th for slice 0421 ...
Creating masked edge and calculating Ct.Th for slice 0431 ...
Creating masked edge and calculating Ct.Th for slice 0441 ...
Calculating bone_surface for R54 ROI1 ...
Calculating mineralizing_surface for R54 ROI1 ...
Writing MSBS_ROI1 images...
Calculating formation_volume for R54 ROI1 ...
Elapsed time is 1068.494259 seconds.
Elapsed time is 1069.405651 seconds.
Loading binary images for specimen R54 ROI2 ...
Processing binary images of specimen R54 ROI2 to retrieve data ...
Calculating MAR for specimen R54 ROI2 ...
Creating masked edges and calculating Ct.Th for R54 ROI2 ...
Creating masked edge and calculating Ct.Th for slice 0699 ...
Creating masked edge and calculating Ct.Th for slice 0709 ...
Creating masked edge and calculating Ct.Th for slice 0719 ...
Creating masked edge and calculating Ct.Th for slice 0729 ...
Creating masked edge and calculating Ct.Th for slice 0739 ...
Creating masked edge and calculating Ct.Th for slice 0749 ...
Creating masked edge and calculating Ct.Th for slice 0759 ...
Creating masked edge and calculating Ct.Th for slice 0769 ...
Creating masked edge and calculating Ct.Th for slice 0779 ...
Creating masked edge and calculating Ct.Th for slice 0789 ...
Creating masked edge and calculating Ct.Th for slice 0799 ...
Creating masked edge and calculating Ct.Th for slice 0809 ...
Creating masked edge and calculating Ct.Th for slice 0819 ...
Creating masked edge and calculating Ct.Th for slice 0829 ...
Creating masked edge and calculating Ct.Th for slice 0839 ...
Creating masked edge and calculating Ct.Th for slice 0849 ...
Creating masked edge and calculating Ct.Th for slice 0859 ...
Creating masked edge and calculating Ct.Th for slice 0869 ...
Creating masked edge and calculating Ct.Th for slice 0879 ...
Creating masked edge and calculating Ct.Th for slice 0889 ...
Creating masked edge and calculating Ct.Th for slice 0899 ...
Creating masked edge and calculating Ct.Th for slice 0909 ...
Creating masked edge and calculating Ct.Th for slice 0919 ...
Creating masked edge and calculating Ct.Th for slice 0929 ...
Creating masked edge and calculating Ct.Th for slice 0939 ...
Creating masked edge and calculating Ct.Th for slice 0949 ...
Calculating bone_surface for R54 ROI2 ...
Calculating mineralizing_surface for R54 ROI2 ...
Writing MSBS_ROI2 images...
Calculating formation_volume for R54 ROI2 ...
Elapsed time is 1030.971949 seconds.
Elapsed time is 1031.942022 seconds.
Loading binary images for specimen R54 ROI3 ...
Processing binary images of specimen R54 ROI3 to retrieve data ...
Calculating MAR for specimen R54 ROI3 ...
Creating masked edges and calculating Ct.Th for R54 ROI3 ...
Creating masked edge and calculating Ct.Th for slice 0451 ...
Creating masked edge and calculating Ct.Th for slice 0461 ...
Creating masked edge and calculating Ct.Th for slice 0471 ...
Creating masked edge and calculating Ct.Th for slice 0481 ...
Creating masked edge and calculating Ct.Th for slice 0491 ...
Creating masked edge and calculating Ct.Th for slice 0501 ...
Creating masked edge and calculating Ct.Th for slice 0511 ...
Creating masked edge and calculating Ct.Th for slice 0521 ...
Creating masked edge and calculating Ct.Th for slice 0531 ...
Creating masked edge and calculating Ct.Th for slice 0541 ...
Creating masked edge and calculating Ct.Th for slice 0551 ...
Creating masked edge and calculating Ct.Th for slice 0561 ...
Creating masked edge and calculating Ct.Th for slice 0571 ...
Creating masked edge and calculating Ct.Th for slice 0581 ...
Creating masked edge and calculating Ct.Th for slice 0591 ...
Creating masked edge and calculating Ct.Th for slice 0601 ...
Creating masked edge and calculating Ct.Th for slice 0611 ...
Creating masked edge and calculating Ct.Th for slice 0621 ...
Creating masked edge and calculating Ct.Th for slice 0631 ...
Creating masked edge and calculating Ct.Th for slice 0641 ...
Creating masked edge and calculating Ct.Th for slice 0651 ...
Creating masked edge and calculating Ct.Th for slice 0661 ...
Creating masked edge and calculating Ct.Th for slice 0671 ...
Creating masked edge and calculating Ct.Th for slice 0681 ...
Calculating bone_surface for R54 ROI3 ...
Calculating mineralizing_surface for R54 ROI3 ...
Writing MSBS_ROI3 images...
Calculating formation_volume for R54 ROI3 ...
Elapsed time is 1002.004838 seconds.
Elapsed time is 1002.826611 seconds.

spec_name =

57

Loading binary images for specimen R57 ROI1 ...
Processing binary images of specimen R57 ROI1 to retrieve data ...
Calculating MAR for specimen R57 ROI1 ...
Creating masked edges and calculating Ct.Th for R57 ROI1 ...
Creating masked edge and calculating Ct.Th for slice 0159 ...
Creating masked edge and calculating Ct.Th for slice 0169 ...
Creating masked edge and calculating Ct.Th for slice 0179 ...
Creating masked edge and calculating Ct.Th for slice 0189 ...
Creating masked edge and calculating Ct.Th for slice 0199 ...
Creating masked edge and calculating Ct.Th for slice 0209 ...
Creating masked edge and calculating Ct.Th for slice 0219 ...
Creating masked edge and calculating Ct.Th for slice 0229 ...
Creating masked edge and calculating Ct.Th for slice 0239 ...
Creating masked edge and calculating Ct.Th for slice 0249 ...
Creating masked edge and calculating Ct.Th for slice 0259 ...
Creating masked edge and calculating Ct.Th for slice 0269 ...
Creating masked edge and calculating Ct.Th for slice 0279 ...
Creating masked edge and calculating Ct.Th for slice 0289 ...
Creating masked edge and calculating Ct.Th for slice 0299 ...
Creating masked edge and calculating Ct.Th for slice 0309 ...
Creating masked edge and calculating Ct.Th for slice 0319 ...
Creating masked edge and calculating Ct.Th for slice 0329 ...
Creating masked edge and calculating Ct.Th for slice 0339 ...
Creating masked edge and calculating Ct.Th for slice 0349 ...
Creating masked edge and calculating Ct.Th for slice 0359 ...
Creating masked edge and calculating Ct.Th for slice 0369 ...
Creating masked edge and calculating Ct.Th for slice 0379 ...
Creating masked edge and calculating Ct.Th for slice 0389 ...
Creating masked edge and calculating Ct.Th for slice 0399 ...
Creating masked edge and calculating Ct.Th for slice 0409 ...
Calculating bone_surface for R57 ROI1 ...
Calculating mineralizing_surface for R57 ROI1 ...
Writing MSBS_ROI1 images...
Calculating formation_volume for R57 ROI1 ...
Elapsed time is 899.207677 seconds.
Elapsed time is 900.214657 seconds.
Loading binary images for specimen R57 ROI2 ...
Processing binary images of specimen R57 ROI2 to retrieve data ...
Calculating MAR for specimen R57 ROI2 ...
Creating masked edges and calculating Ct.Th for R57 ROI2 ...
Creating masked edge and calculating Ct.Th for slice 0669 ...
Creating masked edge and calculating Ct.Th for slice 0679 ...
Creating masked edge and calculating Ct.Th for slice 0689 ...
Creating masked edge and calculating Ct.Th for slice 0699 ...
Creating masked edge and calculating Ct.Th for slice 0709 ...
Creating masked edge and calculating Ct.Th for slice 0719 ...
Creating masked edge and calculating Ct.Th for slice 0729 ...
Creating masked edge and calculating Ct.Th for slice 0739 ...
Creating masked edge and calculating Ct.Th for slice 0749 ...
Creating masked edge and calculating Ct.Th for slice 0759 ...
Creating masked edge and calculating Ct.Th for slice 0769 ...
Creating masked edge and calculating Ct.Th for slice 0779 ...
Creating masked edge and calculating Ct.Th for slice 0789 ...
Creating masked edge and calculating Ct.Th for slice 0799 ...
Creating masked edge and calculating Ct.Th for slice 0809 ...
Creating masked edge and calculating Ct.Th for slice 0819 ...
Creating masked edge and calculating Ct.Th for slice 0829 ...
Creating masked edge and calculating Ct.Th for slice 0839 ...
Creating masked edge and calculating Ct.Th for slice 0849 ...
Creating masked edge and calculating Ct.Th for slice 0859 ...
Creating masked edge and calculating Ct.Th for slice 0869 ...
Creating masked edge and calculating Ct.Th for slice 0879 ...
Creating masked edge and calculating Ct.Th for slice 0889 ...
Creating masked edge and calculating Ct.Th for slice 0899 ...
Creating masked edge and calculating Ct.Th for slice 0909 ...
Creating masked edge and calculating Ct.Th for slice 0919 ...
Calculating bone_surface for R57 ROI2 ...
Calculating mineralizing_surface for R57 ROI2 ...
Writing MSBS_ROI2 images...
Calculating formation_volume for R57 ROI2 ...
Elapsed time is 905.188204 seconds.
Elapsed time is 906.102157 seconds.
Loading binary images for specimen R57 ROI3 ...
Processing binary images of specimen R57 ROI3 to retrieve data ...
Calculating MAR for specimen R57 ROI3 ...
Creating masked edges and calculating Ct.Th for R57 ROI3 ...
Creating masked edge and calculating Ct.Th for slice 0419 ...
Creating masked edge and calculating Ct.Th for slice 0429 ...
Creating masked edge and calculating Ct.Th for slice 0439 ...
Creating masked edge and calculating Ct.Th for slice 0449 ...
Creating masked edge and calculating Ct.Th for slice 0459 ...
Creating masked edge and calculating Ct.Th for slice 0469 ...
Creating masked edge and calculating Ct.Th for slice 0479 ...
Creating masked edge and calculating Ct.Th for slice 0489 ...
Creating masked edge and calculating Ct.Th for slice 0499 ...
Creating masked edge and calculating Ct.Th for slice 0509 ...
Creating masked edge and calculating Ct.Th for slice 0519 ...
Creating masked edge and calculating Ct.Th for slice 0529 ...
Creating masked edge and calculating Ct.Th for slice 0539 ...
Creating masked edge and calculating Ct.Th for slice 0549 ...
Creating masked edge and calculating Ct.Th for slice 0559 ...
Creating masked edge and calculating Ct.Th for slice 0569 ...
Creating masked edge and calculating Ct.Th for slice 0579 ...
Creating masked edge and calculating Ct.Th for slice 0589 ...
Creating masked edge and calculating Ct.Th for slice 0599 ...
Creating masked edge and calculating Ct.Th for slice 0609 ...
Creating masked edge and calculating Ct.Th for slice 0619 ...
Creating masked edge and calculating Ct.Th for slice 0629 ...
Creating masked edge and calculating Ct.Th for slice 0639 ...
Creating masked edge and calculating Ct.Th for slice 0649 ...
Creating masked edge and calculating Ct.Th for slice 0659 ...
Calculating bone_surface for R57 ROI3 ...
Calculating mineralizing_surface for R57 ROI3 ...
Writing MSBS_ROI3 images...
Calculating formation_volume for R57 ROI3 ...
Elapsed time is 875.196559 seconds.
Elapsed time is 875.977097 seconds.

spec_name =

62

Loading binary images for specimen R62 ROI1 ...
Processing binary images of specimen R62 ROI1 to retrieve data ...
Calculating MAR for specimen R62 ROI1 ...
Creating masked edges and calculating Ct.Th for R62 ROI1 ...
Creating masked edge and calculating Ct.Th for slice 0140 ...
Creating masked edge and calculating Ct.Th for slice 0150 ...
Creating masked edge and calculating Ct.Th for slice 0160 ...
Creating masked edge and calculating Ct.Th for slice 0170 ...
Creating masked edge and calculating Ct.Th for slice 0180 ...
Creating masked edge and calculating Ct.Th for slice 0190 ...
Creating masked edge and calculating Ct.Th for slice 0200 ...
Creating masked edge and calculating Ct.Th for slice 0210 ...
Creating masked edge and calculating Ct.Th for slice 0220 ...
Creating masked edge and calculating Ct.Th for slice 0230 ...
Creating masked edge and calculating Ct.Th for slice 0240 ...
Creating masked edge and calculating Ct.Th for slice 0250 ...
Creating masked edge and calculating Ct.Th for slice 0260 ...
Creating masked edge and calculating Ct.Th for slice 0270 ...
Creating masked edge and calculating Ct.Th for slice 0280 ...
Creating masked edge and calculating Ct.Th for slice 0290 ...
Creating masked edge and calculating Ct.Th for slice 0300 ...
Creating masked edge and calculating Ct.Th for slice 0310 ...
Creating masked edge and calculating Ct.Th for slice 0320 ...
Creating masked edge and calculating Ct.Th for slice 0330 ...
Creating masked edge and calculating Ct.Th for slice 0340 ...
Creating masked edge and calculating Ct.Th for slice 0350 ...
Creating masked edge and calculating Ct.Th for slice 0360 ...
Creating masked edge and calculating Ct.Th for slice 0370 ...
Creating masked edge and calculating Ct.Th for slice 0380 ...
Creating masked edge and calculating Ct.Th for slice 0390 ...
Calculating bone_surface for R62 ROI1 ...
Calculating mineralizing_surface for R62 ROI1 ...
Writing MSBS_ROI1 images...
Calculating formation_volume for R62 ROI1 ...
Elapsed time is 842.494098 seconds.
Elapsed time is 843.278853 seconds.
Loading binary images for specimen R62 ROI2 ...
Processing binary images of specimen R62 ROI2 to retrieve data ...
Calculating MAR for specimen R62 ROI2 ...
Creating masked edges and calculating Ct.Th for R62 ROI2 ...
Creating masked edge and calculating Ct.Th for slice 0680 ...
Creating masked edge and calculating Ct.Th for slice 0690 ...
Creating masked edge and calculating Ct.Th for slice 0700 ...
Creating masked edge and calculating Ct.Th for slice 0710 ...
Creating masked edge and calculating Ct.Th for slice 0720 ...
Creating masked edge and calculating Ct.Th for slice 0730 ...
Creating masked edge and calculating Ct.Th for slice 0740 ...
Creating masked edge and calculating Ct.Th for slice 0750 ...
Creating masked edge and calculating Ct.Th for slice 0760 ...
Creating masked edge and calculating Ct.Th for slice 0770 ...
Creating masked edge and calculating Ct.Th for slice 0780 ...
Creating masked edge and calculating Ct.Th for slice 0790 ...
Creating masked edge and calculating Ct.Th for slice 0800 ...
Creating masked edge and calculating Ct.Th for slice 0810 ...
Creating masked edge and calculating Ct.Th for slice 0820 ...
Creating masked edge and calculating Ct.Th for slice 0830 ...
Creating masked edge and calculating Ct.Th for slice 0840 ...
Creating masked edge and calculating Ct.Th for slice 0850 ...
Creating masked edge and calculating Ct.Th for slice 0860 ...
Creating masked edge and calculating Ct.Th for slice 0870 ...
Creating masked edge and calculating Ct.Th for slice 0880 ...
Creating masked edge and calculating Ct.Th for slice 0890 ...
Creating masked edge and calculating Ct.Th for slice 0900 ...
Creating masked edge and calculating Ct.Th for slice 0910 ...
Creating masked edge and calculating Ct.Th for slice 0920 ...
Creating masked edge and calculating Ct.Th for slice 0930 ...
Calculating bone_surface for R62 ROI2 ...
Calculating mineralizing_surface for R62 ROI2 ...
Writing MSBS_ROI2 images...
Calculating formation_volume for R62 ROI2 ...
Elapsed time is 844.474975 seconds.
Elapsed time is 845.286017 seconds.
Loading binary images for specimen R62 ROI3 ...
Processing binary images of specimen R62 ROI3 to retrieve data ...
Calculating MAR for specimen R62 ROI3 ...
Creating masked edges and calculating Ct.Th for R62 ROI3 ...
Creating masked edge and calculating Ct.Th for slice 0400 ...
Creating masked edge and calculating Ct.Th for slice 0410 ...
Creating masked edge and calculating Ct.Th for slice 0420 ...
Creating masked edge and calculating Ct.Th for slice 0430 ...
Creating masked edge and calculating Ct.Th for slice 0440 ...
Creating masked edge and calculating Ct.Th for slice 0450 ...
Creating masked edge and calculating Ct.Th for slice 0460 ...
Creating masked edge and calculating Ct.Th for slice 0470 ...
Creating masked edge and calculating Ct.Th for slice 0480 ...
Creating masked edge and calculating Ct.Th for slice 0490 ...
Creating masked edge and calculating Ct.Th for slice 0500 ...
Creating masked edge and calculating Ct.Th for slice 0510 ...
Creating masked edge and calculating Ct.Th for slice 0520 ...
Creating masked edge and calculating Ct.Th for slice 0530 ...
Creating masked edge and calculating Ct.Th for slice 0540 ...
Creating masked edge and calculating Ct.Th for slice 0550 ...
Creating masked edge and calculating Ct.Th for slice 0560 ...
Creating masked edge and calculating Ct.Th for slice 0570 ...
Creating masked edge and calculating Ct.Th for slice 0580 ...
Creating masked edge and calculating Ct.Th for slice 0590 ...
Creating masked edge and calculating Ct.Th for slice 0600 ...
Creating masked edge and calculating Ct.Th for slice 0610 ...
Creating masked edge and calculating Ct.Th for slice 0620 ...
Creating masked edge and calculating Ct.Th for slice 0630 ...
Creating masked edge and calculating Ct.Th for slice 0640 ...
Creating masked edge and calculating Ct.Th for slice 0650 ...
Creating masked edge and calculating Ct.Th for slice 0660 ...
Creating masked edge and calculating Ct.Th for slice 0670 ...
Calculating bone_surface for R62 ROI3 ...
Calculating mineralizing_surface for R62 ROI3 ...
Writing MSBS_ROI3 images...
Calculating formation_volume for R62 ROI3 ...
Elapsed time is 914.516736 seconds.
Elapsed time is 915.358290 seconds.

spec_name =

65

Loading binary images for specimen R65 ROI1 ...
Processing binary images of specimen R65 ROI1 to retrieve data ...
Calculating MAR for specimen R65 ROI1 ...
Creating masked edges and calculating Ct.Th for R65 ROI1 ...
Creating masked edge and calculating Ct.Th for slice 0145 ...
Creating masked edge and calculating Ct.Th for slice 0155 ...
Creating masked edge and calculating Ct.Th for slice 0165 ...
Creating masked edge and calculating Ct.Th for slice 0175 ...
Creating masked edge and calculating Ct.Th for slice 0185 ...
Creating masked edge and calculating Ct.Th for slice 0195 ...
Creating masked edge and calculating Ct.Th for slice 0205 ...
Creating masked edge and calculating Ct.Th for slice 0215 ...
Creating masked edge and calculating Ct.Th for slice 0225 ...
Creating masked edge and calculating Ct.Th for slice 0235 ...
Creating masked edge and calculating Ct.Th for slice 0245 ...
Creating masked edge and calculating Ct.Th for slice 0255 ...
Creating masked edge and calculating Ct.Th for slice 0265 ...
Creating masked edge and calculating Ct.Th for slice 0275 ...
Creating masked edge and calculating Ct.Th for slice 0285 ...
Creating masked edge and calculating Ct.Th for slice 0295 ...
Creating masked edge and calculating Ct.Th for slice 0305 ...
Creating masked edge and calculating Ct.Th for slice 0315 ...
Creating masked edge and calculating Ct.Th for slice 0325 ...
Creating masked edge and calculating Ct.Th for slice 0335 ...
Creating masked edge and calculating Ct.Th for slice 0345 ...
Creating masked edge and calculating Ct.Th for slice 0355 ...
Creating masked edge and calculating Ct.Th for slice 0365 ...
Creating masked edge and calculating Ct.Th for slice 0375 ...
Creating masked edge and calculating Ct.Th for slice 0385 ...
Creating masked edge and calculating Ct.Th for slice 0395 ...
Calculating bone_surface for R65 ROI1 ...
Calculating mineralizing_surface for R65 ROI1 ...
Writing MSBS_ROI1 images...
Calculating formation_volume for R65 ROI1 ...
Elapsed time is 871.490460 seconds.
Elapsed time is 872.260956 seconds.
Loading binary images for specimen R65 ROI2 ...
Processing binary images of specimen R65 ROI2 to retrieve data ...
Calculating MAR for specimen R65 ROI2 ...
Creating masked edges and calculating Ct.Th for R65 ROI2 ...
Creating masked edge and calculating Ct.Th for slice 0670 ...
Creating masked edge and calculating Ct.Th for slice 0680 ...
Creating masked edge and calculating Ct.Th for slice 0690 ...
Creating masked edge and calculating Ct.Th for slice 0700 ...
Creating masked edge and calculating Ct.Th for slice 0710 ...
Creating masked edge and calculating Ct.Th for slice 0720 ...
Creating masked edge and calculating Ct.Th for slice 0730 ...
Creating masked edge and calculating Ct.Th for slice 0740 ...
Creating masked edge and calculating Ct.Th for slice 0750 ...
Creating masked edge and calculating Ct.Th for slice 0760 ...
Creating masked edge and calculating Ct.Th for slice 0770 ...
Creating masked edge and calculating Ct.Th for slice 0780 ...
Creating masked edge and calculating Ct.Th for slice 0790 ...
Creating masked edge and calculating Ct.Th for slice 0800 ...
Creating masked edge and calculating Ct.Th for slice 0810 ...
Creating masked edge and calculating Ct.Th for slice 0820 ...
Creating masked edge and calculating Ct.Th for slice 0830 ...
Creating masked edge and calculating Ct.Th for slice 0840 ...
Creating masked edge and calculating Ct.Th for slice 0850 ...
Creating masked edge and calculating Ct.Th for slice 0860 ...
Creating masked edge and calculating Ct.Th for slice 0870 ...
Creating masked edge and calculating Ct.Th for slice 0880 ...
Creating masked edge and calculating Ct.Th for slice 0890 ...
Creating masked edge and calculating Ct.Th for slice 0900 ...
Creating masked edge and calculating Ct.Th for slice 0910 ...
Creating masked edge and calculating Ct.Th for slice 0920 ...
Calculating bone_surface for R65 ROI2 ...
Calculating mineralizing_surface for R65 ROI2 ...
Writing MSBS_ROI2 images...
Calculating formation_volume for R65 ROI2 ...
Elapsed time is 880.806406 seconds.
Elapsed time is 881.600368 seconds.
Loading binary images for specimen R65 ROI3 ...
Processing binary images of specimen R65 ROI3 to retrieve data ...
Calculating MAR for specimen R65 ROI3 ...
Creating masked edges and calculating Ct.Th for R65 ROI3 ...
Creating masked edge and calculating Ct.Th for slice 0405 ...
Creating masked edge and calculating Ct.Th for slice 0415 ...
Creating masked edge and calculating Ct.Th for slice 0425 ...
Creating masked edge and calculating Ct.Th for slice 0435 ...
Creating masked edge and calculating Ct.Th for slice 0445 ...
Creating masked edge and calculating Ct.Th for slice 0455 ...
Creating masked edge and calculating Ct.Th for slice 0465 ...
Creating masked edge and calculating Ct.Th for slice 0475 ...
Creating masked edge and calculating Ct.Th for slice 0485 ...
Creating masked edge and calculating Ct.Th for slice 0495 ...
Creating masked edge and calculating Ct.Th for slice 0505 ...
Creating masked edge and calculating Ct.Th for slice 0515 ...
Creating masked edge and calculating Ct.Th for slice 0525 ...
Creating masked edge and calculating Ct.Th for slice 0535 ...
Creating masked edge and calculating Ct.Th for slice 0545 ...
Creating masked edge and calculating Ct.Th for slice 0555 ...
Creating masked edge and calculating Ct.Th for slice 0565 ...
Creating masked edge and calculating Ct.Th for slice 0575 ...
Creating masked edge and calculating Ct.Th for slice 0585 ...
Creating masked edge and calculating Ct.Th for slice 0595 ...
Creating masked edge and calculating Ct.Th for slice 0605 ...
Creating masked edge and calculating Ct.Th for slice 0615 ...
Creating masked edge and calculating Ct.Th for slice 0625 ...
Creating masked edge and calculating Ct.Th for slice 0635 ...
Creating masked edge and calculating Ct.Th for slice 0645 ...
Creating masked edge and calculating Ct.Th for slice 0655 ...
Calculating bone_surface for R65 ROI3 ...
Calculating mineralizing_surface for R65 ROI3 ...
Writing MSBS_ROI3 images...
Calculating formation_volume for R65 ROI3 ...
Elapsed time is 902.125000 seconds.
Elapsed time is 902.927124 seconds.

spec_name =

70

Loading binary images for specimen R70 ROI1 ...
Processing binary images of specimen R70 ROI1 to retrieve data ...
Calculating MAR for specimen R70 ROI1 ...
Creating masked edges and calculating Ct.Th for R70 ROI1 ...
Creating masked edge and calculating Ct.Th for slice 0164 ...
Creating masked edge and calculating Ct.Th for slice 0174 ...
Creating masked edge and calculating Ct.Th for slice 0184 ...
Creating masked edge and calculating Ct.Th for slice 0194 ...
Creating masked edge and calculating Ct.Th for slice 0204 ...
Creating masked edge and calculating Ct.Th for slice 0214 ...
Creating masked edge and calculating Ct.Th for slice 0224 ...
Creating masked edge and calculating Ct.Th for slice 0234 ...
Creating masked edge and calculating Ct.Th for slice 0244 ...
Creating masked edge and calculating Ct.Th for slice 0254 ...
Creating masked edge and calculating Ct.Th for slice 0264 ...
Creating masked edge and calculating Ct.Th for slice 0274 ...
Creating masked edge and calculating Ct.Th for slice 0284 ...
Creating masked edge and calculating Ct.Th for slice 0294 ...
Creating masked edge and calculating Ct.Th for slice 0304 ...
Creating masked edge and calculating Ct.Th for slice 0314 ...
Creating masked edge and calculating Ct.Th for slice 0324 ...
Creating masked edge and calculating Ct.Th for slice 0334 ...
Creating masked edge and calculating Ct.Th for slice 0344 ...
Creating masked edge and calculating Ct.Th for slice 0354 ...
Creating masked edge and calculating Ct.Th for slice 0364 ...
Creating masked edge and calculating Ct.Th for slice 0374 ...
Creating masked edge and calculating Ct.Th for slice 0384 ...
Creating masked edge and calculating Ct.Th for slice 0394 ...
Creating masked edge and calculating Ct.Th for slice 0404 ...
Creating masked edge and calculating Ct.Th for slice 0414 ...
Calculating bone_surface for R70 ROI1 ...
Calculating mineralizing_surface for R70 ROI1 ...
Writing MSBS_ROI1 images...
Calculating formation_volume for R70 ROI1 ...
Elapsed time is 828.809823 seconds.
Elapsed time is 829.761966 seconds.
Loading binary images for specimen R70 ROI2 ...
Processing binary images of specimen R70 ROI2 to retrieve data ...
Calculating MAR for specimen R70 ROI2 ...
Creating masked edges and calculating Ct.Th for R70 ROI2 ...
Creating masked edge and calculating Ct.Th for slice 0660 ...
Creating masked edge and calculating Ct.Th for slice 0670 ...
Creating masked edge and calculating Ct.Th for slice 0680 ...
Creating masked edge and calculating Ct.Th for slice 0690 ...
Creating masked edge and calculating Ct.Th for slice 0700 ...
Creating masked edge and calculating Ct.Th for slice 0710 ...
Creating masked edge and calculating Ct.Th for slice 0720 ...
Creating masked edge and calculating Ct.Th for slice 0730 ...
Creating masked edge and calculating Ct.Th for slice 0740 ...
Creating masked edge and calculating Ct.Th for slice 0750 ...
Creating masked edge and calculating Ct.Th for slice 0760 ...
Creating masked edge and calculating Ct.Th for slice 0770 ...
Creating masked edge and calculating Ct.Th for slice 0780 ...
Creating masked edge and calculating Ct.Th for slice 0790 ...
Creating masked edge and calculating Ct.Th for slice 0800 ...
Creating masked edge and calculating Ct.Th for slice 0810 ...
Creating masked edge and calculating Ct.Th for slice 0820 ...
Creating masked edge and calculating Ct.Th for slice 0830 ...
Creating masked edge and calculating Ct.Th for slice 0840 ...
Creating masked edge and calculating Ct.Th for slice 0850 ...
Creating masked edge and calculating Ct.Th for slice 0860 ...
Creating masked edge and calculating Ct.Th for slice 0870 ...
Creating masked edge and calculating Ct.Th for slice 0880 ...
Creating masked edge and calculating Ct.Th for slice 0890 ...
Creating masked edge and calculating Ct.Th for slice 0900 ...
Creating masked edge and calculating Ct.Th for slice 0910 ...
Calculating bone_surface for R70 ROI2 ...
Calculating mineralizing_surface for R70 ROI2 ...
Writing MSBS_ROI2 images...
Calculating formation_volume for R70 ROI2 ...
Elapsed time is 842.822858 seconds.
Elapsed time is 843.535039 seconds.
Loading binary images for specimen R70 ROI3 ...
Processing binary images of specimen R70 ROI3 to retrieve data ...
Calculating MAR for specimen R70 ROI3 ...
Creating masked edges and calculating Ct.Th for R70 ROI3 ...
Creating masked edge and calculating Ct.Th for slice 0424 ...
Creating masked edge and calculating Ct.Th for slice 0434 ...
Creating masked edge and calculating Ct.Th for slice 0444 ...
Creating masked edge and calculating Ct.Th for slice 0454 ...
Creating masked edge and calculating Ct.Th for slice 0464 ...
Creating masked edge and calculating Ct.Th for slice 0474 ...
Creating masked edge and calculating Ct.Th for slice 0484 ...
Creating masked edge and calculating Ct.Th for slice 0494 ...
Creating masked edge and calculating Ct.Th for slice 0504 ...
Creating masked edge and calculating Ct.Th for slice 0514 ...
Creating masked edge and calculating Ct.Th for slice 0524 ...
Creating masked edge and calculating Ct.Th for slice 0534 ...
Creating masked edge and calculating Ct.Th for slice 0544 ...
Creating masked edge and calculating Ct.Th for slice 0554 ...
Creating masked edge and calculating Ct.Th for slice 0564 ...
Creating masked edge and calculating Ct.Th for slice 0574 ...
Creating masked edge and calculating Ct.Th for slice 0584 ...
Creating masked edge and calculating Ct.Th for slice 0594 ...
Creating masked edge and calculating Ct.Th for slice 0604 ...
Creating masked edge and calculating Ct.Th for slice 0614 ...
Creating masked edge and calculating Ct.Th for slice 0624 ...
Creating masked edge and calculating Ct.Th for slice 0634 ...
Creating masked edge and calculating Ct.Th for slice 0644 ...
Calculating bone_surface for R70 ROI3 ...
Calculating mineralizing_surface for R70 ROI3 ...
Writing MSBS_ROI3 images...
Calculating formation_volume for R70 ROI3 ...
Elapsed time is 764.576166 seconds.
Elapsed time is 765.255023 seconds.

spec_name =

71

Loading binary images for specimen R71 ROI1 ...
Processing binary images of specimen R71 ROI1 to retrieve data ...
Calculating MAR for specimen R71 ROI1 ...
Creating masked edges and calculating Ct.Th for R71 ROI1 ...
Creating masked edge and calculating Ct.Th for slice 0229 ...
Creating masked edge and calculating Ct.Th for slice 0239 ...
Creating masked edge and calculating Ct.Th for slice 0249 ...
Creating masked edge and calculating Ct.Th for slice 0259 ...
Creating masked edge and calculating Ct.Th for slice 0269 ...
Creating masked edge and calculating Ct.Th for slice 0279 ...
Creating masked edge and calculating Ct.Th for slice 0289 ...
Creating masked edge and calculating Ct.Th for slice 0299 ...
Creating masked edge and calculating Ct.Th for slice 0309 ...
Creating masked edge and calculating Ct.Th for slice 0319 ...
Creating masked edge and calculating Ct.Th for slice 0329 ...
Creating masked edge and calculating Ct.Th for slice 0339 ...
Creating masked edge and calculating Ct.Th for slice 0349 ...
Creating masked edge and calculating Ct.Th for slice 0359 ...
Creating masked edge and calculating Ct.Th for slice 0369 ...
Creating masked edge and calculating Ct.Th for slice 0379 ...
Creating masked edge and calculating Ct.Th for slice 0389 ...
Creating masked edge and calculating Ct.Th for slice 0399 ...
Creating masked edge and calculating Ct.Th for slice 0409 ...
Creating masked edge and calculating Ct.Th for slice 0419 ...
Creating masked edge and calculating Ct.Th for slice 0429 ...
Creating masked edge and calculating Ct.Th for slice 0439 ...
Creating masked edge and calculating Ct.Th for slice 0449 ...
Creating masked edge and calculating Ct.Th for slice 0459 ...
Creating masked edge and calculating Ct.Th for slice 0469 ...
Creating masked edge and calculating Ct.Th for slice 0479 ...
Calculating bone_surface for R71 ROI1 ...
Calculating mineralizing_surface for R71 ROI1 ...
Writing MSBS_ROI1 images...
Calculating formation_volume for R71 ROI1 ...
Elapsed time is 827.748294 seconds.
Elapsed time is 828.735004 seconds.
Loading binary images for specimen R71 ROI2 ...
Processing binary images of specimen R71 ROI2 to retrieve data ...
Calculating MAR for specimen R71 ROI2 ...
Creating masked edges and calculating Ct.Th for R71 ROI2 ...
Creating masked edge and calculating Ct.Th for slice 0729 ...
Creating masked edge and calculating Ct.Th for slice 0739 ...
Creating masked edge and calculating Ct.Th for slice 0749 ...
Creating masked edge and calculating Ct.Th for slice 0759 ...
Creating masked edge and calculating Ct.Th for slice 0769 ...
Creating masked edge and calculating Ct.Th for slice 0779 ...
Creating masked edge and calculating Ct.Th for slice 0789 ...
Creating masked edge and calculating Ct.Th for slice 0799 ...
Creating masked edge and calculating Ct.Th for slice 0809 ...
Creating masked edge and calculating Ct.Th for slice 0819 ...
Creating masked edge and calculating Ct.Th for slice 0829 ...
Creating masked edge and calculating Ct.Th for slice 0839 ...
Creating masked edge and calculating Ct.Th for slice 0849 ...
Creating masked edge and calculating Ct.Th for slice 0859 ...
Creating masked edge and calculating Ct.Th for slice 0869 ...
Creating masked edge and calculating Ct.Th for slice 0879 ...
Creating masked edge and calculating Ct.Th for slice 0889 ...
Creating masked edge and calculating Ct.Th for slice 0899 ...
Creating masked edge and calculating Ct.Th for slice 0909 ...
Creating masked edge and calculating Ct.Th for slice 0919 ...
Creating masked edge and calculating Ct.Th for slice 0929 ...
Creating masked edge and calculating Ct.Th for slice 0939 ...
Creating masked edge and calculating Ct.Th for slice 0949 ...
Creating masked edge and calculating Ct.Th for slice 0959 ...
Creating masked edge and calculating Ct.Th for slice 0969 ...
Creating masked edge and calculating Ct.Th for slice 0979 ...
Calculating bone_surface for R71 ROI2 ...
Calculating mineralizing_surface for R71 ROI2 ...
Writing MSBS_ROI2 images...
Calculating formation_volume for R71 ROI2 ...
Elapsed time is 800.113256 seconds.
Elapsed time is 800.931932 seconds.
Loading binary images for specimen R71 ROI3 ...
Processing binary images of specimen R71 ROI3 to retrieve data ...
Calculating MAR for specimen R71 ROI3 ...
Creating masked edges and calculating Ct.Th for R71 ROI3 ...
Creating masked edge and calculating Ct.Th for slice 0489 ...
Creating masked edge and calculating Ct.Th for slice 0499 ...
Creating masked edge and calculating Ct.Th for slice 0509 ...
Creating masked edge and calculating Ct.Th for slice 0519 ...
Creating masked edge and calculating Ct.Th for slice 0529 ...
Creating masked edge and calculating Ct.Th for slice 0539 ...
Creating masked edge and calculating Ct.Th for slice 0549 ...
Creating masked edge and calculating Ct.Th for slice 0559 ...
Creating masked edge and calculating Ct.Th for slice 0569 ...
Creating masked edge and calculating Ct.Th for slice 0579 ...
Creating masked edge and calculating Ct.Th for slice 0589 ...
Creating masked edge and calculating Ct.Th for slice 0599 ...
Creating masked edge and calculating Ct.Th for slice 0609 ...
Creating masked edge and calculating Ct.Th for slice 0619 ...
Creating masked edge and calculating Ct.Th for slice 0629 ...
Creating masked edge and calculating Ct.Th for slice 0639 ...
Creating masked edge and calculating Ct.Th for slice 0649 ...
Creating masked edge and calculating Ct.Th for slice 0659 ...
Creating masked edge and calculating Ct.Th for slice 0669 ...
Creating masked edge and calculating Ct.Th for slice 0679 ...
Creating masked edge and calculating Ct.Th for slice 0689 ...
Creating masked edge and calculating Ct.Th for slice 0699 ...
Creating masked edge and calculating Ct.Th for slice 0709 ...
Creating masked edge and calculating Ct.Th for slice 0719 ...
Calculating bone_surface for R71 ROI3 ...
Calculating mineralizing_surface for R71 ROI3 ...
Writing MSBS_ROI3 images...
Calculating formation_volume for R71 ROI3 ...
Elapsed time is 757.145826 seconds.
Elapsed time is 757.745283 seconds.
%}

